# Generated by Django 4.0.1 on 2023-07-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_type', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=255)),
                ('device_id', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
