# Generated by Django 4.0.1 on 2023-07-21 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublishData',
            new_name='CloudPublishData',
        ),
    ]
