# Generated by Django 4.0.1 on 2023-06-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('alias', models.CharField(max_length=100)),
                ('client_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('server_topic', models.CharField(blank=True, max_length=100, null=True)),
                ('port', models.IntegerField(default=1883)),
                ('broker_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
    ]
