# Generated by Django 4.0.1 on 2023-07-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasimulate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apdevice',
            name='mac_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
